spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://infra-internal:8848
        # 引用bootstrap.yml中的spring.application.name
        service: cloud-order-service
        # 服务注册的元数据
        metadata:
          version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 18082